#!/usr/bin/env bash
# retro-extract.sh — Extract actionable lessons from the latest /rrr retro
# and save them as injectable context for the next session spawn.
#
# Claude Code injects ugrep as grep — breaks regex patterns with --flag-like strings
unset -f grep 2>/dev/null
#
# Called by prompt-inject.sh at SessionStart (regenerates for the NEXT session),
# or manually:  bash claude/hooks/retro-extract.sh [oracle-root]
#
# Inspired by Oracle Council's retro-extract.sh (federation exchange 2026-04-16).
# Loop: SessionStart → prompt-inject.sh reads spawn-context.md (prior session) →
#       calls retro-extract.sh to regenerate it for the next spawn.
#
# Output: $PSI/memory/spawn-context.md — read by prompt-inject.sh at SessionStart.
# Budget: max 3000 tokens (~12K chars) — per Oracle Council recommendation.

set -uo pipefail
# Note: -e omitted intentionally. grep/head/awk return non-zero in normal
# operation (no matches, broken pipe). We handle errors explicitly.

MAX_CHARS=12000  # ~3K tokens budget

# --- Oracle root detection (same pattern as /rrr skill) ---
ORACLE_ROOT="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
if [ -f "$ORACLE_ROOT/CLAUDE.md" ] && { [ -d "$ORACLE_ROOT/ψ" ] || [ -L "$ORACLE_ROOT/ψ" ]; }; then
  PSI="$ORACLE_ROOT/ψ"
else
  echo "⚠️ Not in oracle repo. Skipping retro-extract."
  exit 0
fi

RETRO_DIR="$PSI/memory/retrospectives"
LEARNINGS_DIR="$PSI/memory/learnings"
SPAWN_FILE="$PSI/memory/spawn-context.md"

# --- Find latest retro ---
LATEST_RETRO=$(find "$RETRO_DIR" -name '*.md' -type f 2>/dev/null | sort | tail -1)
if [ -z "$LATEST_RETRO" ]; then
  echo "No retrospectives found. Skipping."
  exit 0
fi

# --- Find recent learnings (last 7 days) ---
RECENT_LEARNINGS=$(find "$LEARNINGS_DIR" -name '*.md' -type f -mtime -7 2>/dev/null | sort -r | head -10)

# --- Extract key sections from latest retro ---
# Pull: Lessons Learned, Next Steps, Key friction points
RETRO_EXTRACT=""
if [ -f "$LATEST_RETRO" ]; then
  # Extract target sections through the line before the next ## header.
  RETRO_EXTRACT=$(awk '
    /^## / {
      in_section = /^## (Honest Feedback|Lessons Learned|Next Steps)$/
    }
    in_section { print }
  ' "$LATEST_RETRO" | head -60)
fi

# --- Build spawn context ---
{
  echo "# Spawn Context (auto-generated by retro-extract.sh)"
  echo ""
  echo "This is inherited context from prior sessions. You are a new session"
  echo "that received this context — not the same session that created it."
  echo "(Rule 6: identity ≠ continuity)"
  echo ""
  echo "Generated: $(date '+%Y-%m-%d %H:%M %Z')"
  echo "Source retro: $(basename "$LATEST_RETRO")"
  echo ""

  # Latest retro key points
  if [ -n "$RETRO_EXTRACT" ]; then
    echo "## From Latest Retrospective"
    echo ""
    echo "$RETRO_EXTRACT"
    echo ""
  fi

  # Recent learnings (titles + first lines)
  if [ -n "$RECENT_LEARNINGS" ]; then
    echo "## Recent Learnings (last 7 days)"
    echo ""
    while IFS= read -r learning; do
      [ -f "$learning" ] || continue
      TITLE=$(head -1 "$learning" | sed 's/^#* //')
      # First non-empty, non-header line as summary
      SUMMARY=$(grep -v '^#\|^$\|^---\|^\*\*' "$learning" 2>/dev/null | head -2 | tr '\n' ' ' | cut -c1-200 || true)
      echo "- **$TITLE**: $SUMMARY"
    done <<< "$RECENT_LEARNINGS"
    echo ""
  fi

  # Handoff context (latest inbox)
  LATEST_HANDOFF=$(find "$PSI/inbox/handoff" -name '*.md' -type f -mtime -7 2>/dev/null | sort | tail -1)
  if [ -n "$LATEST_HANDOFF" ] && [ -f "$LATEST_HANDOFF" ]; then
    echo "## Latest Handoff"
    echo ""
    head -30 "$LATEST_HANDOFF"
    echo ""
  fi
} > "${SPAWN_FILE}.tmp"

# --- Enforce token budget ---
CHAR_COUNT=$(wc -c < "${SPAWN_FILE}.tmp")
if [ "$CHAR_COUNT" -gt "$MAX_CHARS" ]; then
  head -c "$MAX_CHARS" "${SPAWN_FILE}.tmp" > "$SPAWN_FILE"
  echo "" >> "$SPAWN_FILE"
  echo "[retro-extract: truncated at ${MAX_CHARS} chars (~3K tokens budget]" >> "$SPAWN_FILE"
else
  mv "${SPAWN_FILE}.tmp" "$SPAWN_FILE"
fi
rm -f "${SPAWN_FILE}.tmp"

echo "[retro-extract] spawn-context.md updated ($(wc -c < "$SPAWN_FILE") chars)"
