#!/usr/bin/env bash
# generate-guard-patterns.sh — Derive git-guard / pre-guard bash patterns from projects.yaml.
# Called by fleet-sync.sh. Output: claude/git-guard/_generated-patterns.sh (sourced by guards).
# Single source: fleet/projects.yaml. NEVER hand-edit the generated file.
set -uo pipefail

WF="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
REGISTRY="$WF/fleet/projects.yaml"
OUT="$WF/claude/git-guard/_generated-patterns.sh"

[ -f "$REGISTRY" ] || { echo "✗ registry missing: $REGISTRY" >&2; exit 1; }

query_registry() {
  local field="$1" value="$2"
  python3 -c "
import re
text = open('$REGISTRY').read()
for block in re.split(r'\n(?=- name:)', text.strip()):
    m = re.search(r'- name:\s*(\S+)', block)
    if not m: continue
    name = m.group(1)
    st = re.search(r'status:\s*(\S+)', block)
    if st and st.group(1) in ('archived','decommissioned'): continue
    f = re.search(r'$field:\s*(\S+)', block)
    if f and f.group(1) == '$value': print(name)
"
}

PRODUCT_NAMES=$(query_registry lane heavyweight)
HOOK_BLOCKED_NAMES=$(query_registry guard hook-blocked)

PRODUCT_PATTERN=$(echo "$PRODUCT_NAMES" | tr '\n' '|' | sed 's/|$//')
HOOK_BLOCKED_PATTERN=$(echo "$HOOK_BLOCKED_NAMES" | tr '\n' '|' | sed 's/|$//')

cat > "$OUT" << GENEOF
# GENERATED by scripts/generate-guard-patterns.sh — DO NOT HAND-EDIT.
# Source: fleet/projects.yaml. Regenerated by fleet-sync.sh.
# Sourced by claude/git-guard/_classify.sh and claude/hooks/pre-guard.sh.

PRODUCT_REPO_PATTERN="$PRODUCT_PATTERN"
HOOK_BLOCKED_REPO_PATTERN="$HOOK_BLOCKED_PATTERN"

is_product_repo() { case "\$1" in $PRODUCT_PATTERN) return 0 ;; *) return 1 ;; esac; }
is_hook_blocked() { case "\$1" in $HOOK_BLOCKED_PATTERN) return 0 ;; *) return 1 ;; esac; }
GENEOF

PC=$(echo "$PRODUCT_NAMES" | grep -c . || echo 0)
HC=$(echo "$HOOK_BLOCKED_NAMES" | grep -c . || echo 0)
echo "✓ generated $OUT ($PC product, $HC hook-blocked)"
