#!/usr/bin/env bash
# oracle-build.sh — Dual-render CLAUDE.md (Claude) + AGENTS.md (Codex) from ONE doctrine source.
#
# Usage:
#   oracle-build.sh --global        Build Gale-Framework global targets (the ONLY mode):
#                                     claude/CLAUDE.md       = core + claude
#                                     codex/instructions.md  = core + codex
#
# Single-source dual-render (kills CLAUDE.md↔AGENTS.md drift):
#   doctrine/core.md    shared rules BOTH engines obey
#   doctrine/claude.md  Layer-1 Oracle (orchestrator) overlay
#   doctrine/codex.md   Layer-2/3 worker (coding hands) overlay
#
#   Layered context (2026-06-13): doctrine renders to the GLOBAL layer ONLY —
#   ~/.claude/CLAUDE.md and ~/.codex/instructions.md (symlinks into WF) load in EVERY
#   session alongside the cwd file. Per-oracle files are therefore IDENTITY-ONLY:
#
#   CLAUDE.md = oracle-<name>-claude.md   (Claude identity — doctrine arrives via global)
#   AGENTS.md = oracle-<name>-agents.md   (Codex identity — doctrine arrives via global)
#
# Generated files are NEVER hand-edited — edit the fragment, re-run. "Copy files, not symlinks."

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

GEN_HDR_1="<!-- Generated by scripts/oracle-build.sh — do not hand-edit. -->"

render() {  # render OUTPUT_FILE EDIT_HINT FRAGMENT...
  local out="$1"; local hint="$2"; shift 2
  {
    echo "$GEN_HDR_1"
    echo "<!-- $hint -->"
    echo ""
    local first=1
    for frag in "$@"; do
      [ -f "$frag" ] || { echo "✗ missing fragment: $frag" >&2; exit 1; }
      [ $first -eq 1 ] || echo ""
      cat "$frag"
      first=0
    done
  } > "$out"
  echo "✓ $out ($(wc -l < "$out") lines) ← $(echo "$@" | tr ' ' ',')"
}

# ---- Global mode: Gale-Framework global targets ----
if [ "${1:-}" = "--global" ]; then
  D="claude/doctrine"
  [ -d "$D" ] || { echo "✗ run --global from Gale-Framework root (no $D)" >&2; exit 1; }
  render "claude/CLAUDE.md"      "Edit claude/doctrine/{core,claude}.md, then re-run oracle-build.sh --global." "$D/core.md" "$D/claude.md"
  render "codex/instructions.md" "Edit claude/doctrine/{core,codex}.md, then re-run oracle-build.sh --global."  "$D/core.md" "$D/codex.md"
  exit 0
fi

# ---- Per-oracle mode RETIRED (2026-06-13) ----
# Layered context made per-oracle CLAUDE.md identity-ONLY, so the rendered file was a
# byte-identical copy of oracle-<name>-claude.md + a 3-line header — pure indirection.
# Each oracle's CLAUDE.md / AGENTS.md is now the hand-edited identity itself (Claude/Codex
# read it directly; fleet doctrine arrives via the global ~/.claude/CLAUDE.md and
# ~/.codex/AGENTS.md). The structural-guard lint in fleet-sync keeps them identity-only.
if [ "${1:-}" != "--global" ]; then
  echo "oracle-build.sh: per-oracle mode is retired — CLAUDE.md/AGENTS.md ARE the identity (edit them directly)." >&2
  echo "Only '--global' remains (renders doctrine → WF/claude/CLAUDE.md + codex/instructions.md)." >&2
  exit 0
fi
